# Generated by Django 4.0.3 on 2022-03-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_back',
            field=models.ImageField(default='yebrhan_back.jpg', upload_to=''),
        ),
    ]
