# Generated by Django 4.0.3 on 2022-04-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_back',
            field=models.ImageField(default='yebrhan_back.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_front',
            field=models.ImageField(default='yebrhan_enat.jpg', upload_to=''),
        ),
    ]
