# Generated by Django 4.0.3 on 2022-04-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_book_image_back_alter_book_image_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(null=True, to='base.packages'),
        ),
        migrations.CreateModel(
            name='PackageQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.packages')),
            ],
        ),
    ]
