# Generated by Django 4.0.3 on 2022-04-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_packages_packagequantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
