# Generated by Django 3.2.9 on 2022-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='chat_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
