# Generated by Django 4.0.4 on 2022-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
